server:
  port: 9999

spring:
  data:
    mongodb:
      port: 27017
      database: auth

management:
  server:
    port: 8081
  health:
    mongo:
      enabled: true
  endpoint:
    health:
      show-details: always